### ISSUE TITLE
Update version tags

### ISSUE THREAD

**Issue by davidgorges** [rpocklin/angular-timeline#1]
Hey,

your bower.json has a version attribute that hast the valu 1.0. [Bower ignores the version attribute](https://github.com/bower/bower.json-spec) anyway, so better remove it or keep updated.

Additionally, could you create version tags for the latest 1.2 release? 1.1 has no entry in the changelog, and that's the only currently available version in bower. The README seems to reflect 1.2 which is dev-master I guess?

**Comment by rpocklin** [comment]
Hi David,

Thanks for pointing out the 1.2 tag wasn't pushed, it's there now :)
