### ISSUE TITLE
Horizontal Timeline

### ISSUE THREAD

**Issue by novitoll** [rpocklin/angular-timeline#12]
Is there any option to turn vertical timeline into horizontal?

**Comment by rpocklin** [comment]
Sure, just rotate your screen a bit :)

Seriously, no there isn't, but you could probably get creative with CSS and get somewhere.

Depends how you want it to look structurally.

**Comment by novitoll** [comment]
:) I meant, if there is any option, e.g. flag that render it horizontally. Ok, thanks, then the solution is the custom CSS.

**Comment by rpocklin** [comment]
Nah not really, but if you make some nice CSS styling and want to include it i'll be happy to accept a PR and add a demo on here.
