### ISSUE TITLE
Can you make it compatible with Angular 1.4?

### ISSUE THREAD

**Issue by OzzieOrca** [rpocklin/angular-timeline#16]
I'm having to use a resolution to angular 1.4.7 and angular-sanitize 1.4.7. It seems to work fine running 1.4.7. If it could be updated that would be great. Thanks!

I can make a PR changing the versions in bower.json if that would be helpful.

**Comment by rpocklin** [comment]
I noticed angular-sanitise was ~ not ^ (unlike angular) and corrected it.  Remove and re-install `angular-timeline` and it should be good to go.  Reason not to bump to 1.4 is because it doesn't really _need_ 1.4, and others can still use it with 1.3.x

**Comment by OzzieOrca** [comment]
Awesome that takes care of the issue and makes sense. Thanks!
