### ISSUE TITLE
Force/set panel alignment

### ISSUE THREAD

**Issue by somada141** [rpocklin/angular-timeline#18]
Hi and thanks a lot for the lovely plugin.

I went through the docs and example, even the code, and I can't figure out how (and whether) it'd be possible to 'force' the alignment of the panel to be all to the left/right (as when used in a small column the panels are too narrow when alternating between left and right).

Can this be done?

Cheers!

**Comment by rpocklin** [comment]
This is by far the most requested feature :)

It is just CSS, take a look at the included .css and you'll see it alternates left -> right.  If you make it smaller (ie. mobile size) it responds by doing what you want.

This is such a requested feature i'll update the CSS to have a class 'all-left' or 'all-right' to do what you suggest.

Feel free to submit a PR.

**Comment by somada141** [comment]
Thanks for the response, it comes as no surprise people want justification :). Sadly I'm really bad with CSS and I wouldn't know how to do it but I can take a looksie :)

Thanks again!

**Comment by somada141** [comment]
Can you point me to what part of the CSS would have to change? I can easily switch the 'float' settings to all be left/right but that's about it, can't get the central line to go left/right or the panel extrusions to point to the right direction

**Comment by rpocklin** [comment]
I'll get to this in the next week or so and bump the version.

**Comment by armandchard** [comment]
I'm interested too. 
Please tell me when we can easily align all content to left or right.
Cheers

**Comment by vankeer** [comment]
@armandchard I have an open PRQ for this: https://github.com/rpocklin/angular-timeline/pull/17 So if you need it now, you can use my fork.

**Comment by rpocklin** [comment]
Landed in `v1.6.1`

**Comment by armandchard** [comment]
Thank you, I upgrade right now :)

**Comment by armandchard** [comment]
I don't understand but it's seems that doesn't work for me...

There's my html code : 
< timeline-event ng-repeat="suivi in suivis" side=left>

**Comment by rpocklin** [comment]
Can you send a full plunkr?  Perhaps do a diff between your code and the example demo in the repo, and check the console for any errors.  Also what doesn't work exactly?

**Comment by rpocklin** [comment]
Btw you are missing quotes in the side="left" text you gave in your example.
