### ISSUE TITLE
Make library available through CDN and NPM

### ISSUE THREAD

**Issue by crissdev** [rpocklin/angular-timeline#2]
Have you considered making the library available through cdnjs or jsdelivr? Publishing it to npm would also be helpful.

**Comment by rpocklin** [comment]
Agree I should publish this to NPM :)  Thanks for reminding me.

_cdnjs_ and _jsdelivr_ I see as less important - i'd recommend using bower to install locally instead.

**Comment by rpocklin** [comment]
Published at https://www.npmjs.com/package/angular-timeline - no plans for the CDNs at this stage sorry.

**Comment by crissdev** [comment]
Thanks.
