### ISSUE TITLE
How can i force float right whatever the size/width ? 

### ISSUE THREAD

**Issue by sam2x** [rpocklin/angular-timeline#27]
Hey, 

Thanks for your lib. 
When width is greater than 767px, a media-query center the timeline, and all elements are adjusting to the left or the right. How can i force the element to be in a column (whatever the width of the screen) the same way it is displayed in mobile device / "little screen" ? 

Regards

**Comment by sam2x** [comment]
Ok i overrided the css, i almost make it works, but something is wrong. Here the css :

```
@media only screen {
   ul.timeline:before {
     left: 40px;
   }
   ul.timeline li timeline-badge {
    left: 15px;
    margin-left: 0;
    top: 36px;
  }
  ul.timeline li timeline-panel:after {
    border-left-width: 0;
    border-right-width: 14px;
    left: -14px;
   right: auto;
   top: 47px;
  }
  .timeline li.timeline-inverted timeline-panel {
    float: right;
  }
  ul.timeline li timeline-panel {
    float: right;
  }
  ul.timeline li timeline-panel {
    width: calc(100% - 85px);
    width: -moz-calc(100% - 85px);
    width: -webkit-calc(100% - 85px);
 }
}
```

I have a weird bug in the width calculation. My less parser understand "85px" as "85%", so the resulting width is : "15%". Anyone has experienced the same problem ?

**Comment by sam2x** [comment]
Ok make it works! The solution with Less parser was to let the client browser calculating the experession.
So instead of : 

```
 ul.timeline li timeline-panel {
    width: calc(100% - 85px);
    width: -moz-calc(100% - 85px);
    width: -webkit-calc(100% - 85px);
 }
```

I modified to : 

```
 ul.timeline li timeline-panel {
    width: calc(~'100% - 85px');
    width: -moz-calc(~'100% - 85px');
    width: -webkit-calc(~'100% - 85px');
 }
```

Now the width is correctly calculated. Sorry to have filled this issue. Hope it helps others peoples.
Regards.

**Comment by rpocklin** [comment]
You'll find the `Demo` link on the main page has a good example of 'all left' or 'all right' with the buttons up the top.  Look at the source to understand what it's doing.

**Comment by sam2x** [comment]
Hey @rpocklin, thanks you for your answer, but the problem wasnt about the "side" feature which allow to set left/right side on "box". My problem was about disabling the "default" layout (when width > 767px) which split the timeline in "two side" with the "time bar" in the middle, so i wanted it to be stick on the left side even if width > 767px.
