### ISSUE TITLE
Update library version on npm

### ISSUE THREAD

**Issue by zorator** [rpocklin/angular-timeline#28]
On npm, version is 1.2.1.
Allso, the github link seems to be wrong

**Comment by rpocklin** [comment]
Ok, will get to this one shortly.

**Comment by dv336699** [comment]
@zorator you can install by running `npm install rpocklin/angular-timeline`

**Comment by zorator** [comment]
@diego-vieira the issue is on the version offered by npm, which is 1.2.1. On github, the version is 1.6.2.

**Comment by zorator** [comment]
By the way, I just find out that the github repo specified on [npmjs.com](https://www.npmjs.com/package/angular-timeline) was [github.com/npm/npm](github.com/npm/npm).

**Comment by dv336699** [comment]
@zorator I know, I just come to this issue because of the same reason, but to resolve your issue on getting the not up to date version you can use the command I mentioned.

**Comment by rpocklin** [comment]
All fixed.

**Comment by zorator** [comment]
thanks !
