### ISSUE TITLE
Bower.json not containing CSS file // unnecessary dependencies

### ISSUE THREAD

**Issue by frankthelen** [rpocklin/angular-timeline#3]
Hi Robert,

this is more a question about your bower.json...

"main" only specifies JS to be installed but does not contain any CSS. As a result, I have to add it manually to my index.html. If you add the CSS file to the "main" section, it'll be added automatically to my index.html. Unually this is "/dist/angular-timeline.css" then, since it is built from scss.

In addition, I am wondering why you have dependencies to "angular-bootstrap" and "angular-ui-router". As a result, I have these libraries automatically added to my index.html. Why are these required? The original Bootsnip at least doesn't. 

Many thanks for making this available,
Frank

**Comment by rpocklin** [comment]
Thanks - they are good questions.

About excluding the CSS, that was mainly to allow people to choose which CSS or SASS file they wanted to include, depending on whether they are using bootstrap or not.

re: dependencies - thanks that's a good pickup.  I extracted this from a project that used those and it seems they didn't want to leave :)  I'll try stripping them out and update the repo.

**Comment by frankthelen** [comment]
Fixed. Thanks a lot. :-)
