### ISSUE TITLE
How to align the vertical line on one side ?

### ISSUE THREAD

**Issue by siyadmhd** [rpocklin/angular-timeline#31]
Currently it is always positioned at center.

**Comment by rpocklin** [comment]
If you shrink your viewport down to 1024px width the vertical line will be on the LHS.  This is just CSS so feel free to play around and if you have a good solution create a PR.

**Comment by lewma** [comment]
If you look in the dist/angular-timeline.css file you'll see two @media sections.  Comment out the first @media definition completely then remove "and (max-width:767px)" from the second definition.

This will result in a single @media definition that spans the entire width. 

This is what I did and it seems to be working fine for me.
