### ISSUE TITLE
can you make it compatible with angular 1.3?

### ISSUE THREAD

**Issue by gsemet** [rpocklin/angular-timeline#5]
Hi. because I have: 

```
Unable to find suitable version for angular
```

when installing angular-timeline.

**Comment by rpocklin** [comment]
Sorry, resolutions in `bower.json` got pushed accidently.  Try now.

**Comment by gsemet** [comment]
work like a charm ! thanks!

**Comment by arielwb** [comment]
Hi, angular 1.3 is still suported?
because I get:
   Unable to find suitable version for angular
when installing angular-timeline.

Thanks!
